name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 12.3.1
          run_install: true
      - name: Build dist
        run: pnpm run dist
      - name: Publish NPM
        run: npm publish
